### PR TITLE
only 1 session

### PR DESCRIPTION
**Pull request by Nirlep5252**
instead of creating a new `aiohttp.ClientSession()` in the for loop, changed it so that we can reuse the same session for all requests when the file is run

### CODE REVIEW

**Comment by denzven** [comment]
cool.. gotta update this in the bot too!

**Comment by Nirlep5252** [comment]
poggers

**Comment by denzven** [comment]
but it has a depreciation warning for using it that way.. 🤔 

```
DeprecationWarning: The object should be created within an async function
  session = aiohttp.ClientSession()
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001C484D59FD0>
```

**Comment by Nirlep5252** [comment]
interesting

**Comment by Nirlep5252** [comment]
The client session error is because i forgot to close the session... :monkaS:
`await session.close()`

But I'm not sure why you are getting that warning because I use it in everywhere but don't get the warning 🤔 
https://awish-go.to-sleep.xyz/krkq65kqf9a

**Comment by denzven** [comment]
Cool.. Lemme add that that line and check.. 👍

**Pull request merged**
